name: Deploy Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag : ${{steps.image_build.outputs.images_tag}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet
    
    - id: image_build
      name: Build and push Docker image
      run: |
        docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/main/ms-user-management:${{ github.sha }} .
        docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/main/ms-user-management:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ms-user-management \
        --image asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/main/ms-user-management:${{ github.sha }} \
        --region asia-southeast1 \
        --platform managed \
        --allow-unauthenticated \
        --max-instances=10 \
        --set-env-vars DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_NAME=${{ secrets.DB_NAME }} \
        --memory=2Gi \
        --concurrency=80 \
        --timeout=300s \
        --use-http2